"""Add password to User

Revision ID: 691ae072578a
Revises: 8036b3041cd8
Create Date: 2025-09-26 17:29:11.427392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691ae072578a'
down_revision = '8036b3041cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
       batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False, server_default=""))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
